### ISSUE TITLE
关于SQL文件

### ISSUE THREAD

**Issue by YfNightWind** [gcloudlab/disk-server#3]
似乎不太完整呀，没有public和社区的表，可以更新一下吗

**Comment by yesmore** [comment]
> 似乎不太完整呀，没有public和社区的表，可以更新一下吗

emm对，你可以根据 model 先写一下，过两天补充。

**Comment by YfNightWind** [comment]
> > 似乎不太完整呀，没有public和社区的表，可以更新一下吗
> 
> emm对，你可以根据 model 先写一下，过两天补充。

好的，谢谢！

**Comment by yesmore** [comment]
03fc27f7946949f5be512ae3d16bca84351a0088
